apiVersion: v1
kind: Service
metadata:
  name: shortener
  labels:
    app: content-shortener
spec:
  selector:
    app: content-shortener
  ports:
    - name: http
      port: 8094
      targetPort: 8094
